### ISSUE TITLE
窗口组件下移

### ISSUE THREAD

**Issue by etclij** [freeseawind/littleluck#10]
使用非默认的rootpanel 的时候：
 UIManager.put(LuckUIClassKey.ROOTPANEUI, LuckMetalRootPaneUI.class.getName());
会出现组件下移的情况
然后还有menubar设置为空， 但是会出现一条线的bug

**Comment by freeseawind** [comment]
已确认：
1、UIManager.put(LuckUIClassKey.ROOTPANEUI, LuckMetalRootPaneUI.class.getName());
会出现组件下移的情况 (BUG)
2、Menubar设置为空， 但是会出现一条线，因为你的Menubar的大小没有设置或者没有隐藏（非BUG）
