### ISSUE TITLE
这抄袭？

### ISSUE THREAD

**Issue by huipengcheng** [freeseawind/littleluck#13]
大家看看这个https://github.com/JackJiang2011/beautyeye。

**Comment by freeseawind** [comment]
你用源码比对工具比对下，不知道怎么抄袭了

**Comment by huipengcheng** [comment]
<img width="691" alt="2019-03-03 23 01 52" src="https://user-images.githubusercontent.com/42164573/53697099-a1fec680-3e08-11e9-9f9d-58f8dcfeeefe.png">
<img width="737" alt="2019-03-03 23 03 45" src="https://user-images.githubusercontent.com/42164573/53697101-a2975d00-3e08-11e9-8707-f60e87d502f3.png">
上面是别人的  下面是你的

**Comment by huipengcheng** [comment]
程序名称相同，和你图标都一样
<img width="881" alt="2019-03-03 23 05 21" src="https://user-images.githubusercontent.com/42164573/53697114-d70b1900-3e08-11e9-86db-cd9983fee91d.png">


还有帮助sh手册什么的，我就不一一截图了

**Comment by huipengcheng** [comment]
地址多加了个句号
https://github.com/JackJiang2011/beautyeye
是这个

**Comment by freeseawind** [comment]
那个是swingset3 是JDK的demo,你可以自己去查下，另外请进行源码比较

**Comment by freeseawind** [comment]
注意细节，那个滚动条的效果，能用beautyeye实现出来吗，自己好好看下

**Comment by photographzzz** [comment]
<img width="691" alt="2019-03-03 23 01 52" src="https://user-images.githubusercontent.com/42164573/53708540-ea50cf80-3e6e-11e9-9e28-f521f3f2a9f6.png">
<img width="881" alt="2019-03-03 23 05 21" src="https://user-images.githubusercontent.com/42164573/53708542-ec1a9300-3e6e-11e9-837a-38ca9a9e3d45.png">

这两个滚动条效果不一样吗
